import { Product } from '../../types/product';

export const mockProducts: Product[] = [
  // Notebooks (NOTE)
  {
    id: 'ELEC-NOTE-001',
    name: 'MacBook Pro M2 14"',
    description: 'MacBook Pro 14" com chip M2 Pro, 16GB RAM, SSD 512GB',
    price: 14999.99,
    originalPrice: 16999.99,
    image: '/images/products/macbook-pro-m2.jpg',
    brand: 'Apple',
    category: 'notebooks',
    rating: 4.9,
    reviews: 156,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isPromotion: true
  },
  {
    id: 'ELEC-NOTE-002',
    name: 'Dell XPS 13 Plus',
    description: 'Dell XPS 13 Plus com Intel Core i7, 16GB RAM, SSD 512GB',
    price: 9999.99,
    originalPrice: 11999.99,
    image: '/images/products/dell-xps-13-plus.jpg',
    brand: 'Dell',
    category: 'notebooks',
    rating: 4.8,
    reviews: 123,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-NOTE-003',
    name: 'Lenovo Legion 5 Pro',
    description: 'Notebook gamer com RTX 3070, AMD Ryzen 7, 16GB RAM',
    price: 8999.99,
    originalPrice: 10999.99,
    image: '/images/products/legion-5-pro.jpg',
    brand: 'Lenovo',
    category: 'notebooks',
    rating: 4.7,
    reviews: 89,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-NOTE-004',
    name: 'Notebook Lenovo Legion 5',
    description: 'Notebook gamer com RTX 3060, AMD Ryzen 5, 16GB RAM',
    price: 6999.99,
    originalPrice: 8499.99,
    image: '/images/products/legion-5.jpg',
    brand: 'Lenovo',
    category: 'notebooks',
    rating: 4.6,
    reviews: 78,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-NOTE-005',
    name: 'MacBook Air M1',
    description: 'MacBook Air com chip M1, 8GB RAM, SSD 256GB',
    price: 7999.99,
    originalPrice: 8999.99,
    image: '/images/products/macbook-air-m1.jpg',
    brand: 'Apple',
    category: 'notebooks',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-NOTE-006',
    name: 'Notebook Dell XPS 13',
    description: 'Dell XPS 13 com Intel Core i5, 8GB RAM, SSD 512GB',
    price: 7499.99,
    originalPrice: 8999.99,
    image: '/images/products/dell-xps-13.jpg',
    brand: 'Dell',
    category: 'notebooks',
    rating: 4.7,
    reviews: 167,
    inStock: true,
    isPromotion: true
  },

  // Tablets (TAB)
  {
    id: 'ELEC-TAB-001',
    name: 'iPad Pro 12.9" (M2)',
    description: 'iPad Pro 12.9" com chip M2, 256GB, Wi-Fi + 5G',
    price: 11999.99,
    originalPrice: 13999.99,
    image: '/images/products/ipad-pro-m2.jpg',
    brand: 'Apple',
    category: 'tablets',
    rating: 4.9,
    reviews: 89,
    inStock: true,
    isNew: true,
    isPromotion: true
  },
  {
    id: 'ELEC-TAB-002',
    name: 'Samsung Galaxy Tab S9 Ultra',
    description: 'Tablet Android premium com tela de 14.6", 256GB, Wi-Fi + 5G',
    price: 9999.99,
    originalPrice: 11999.99,
    image: '/images/products/tab-s9-ultra.jpg',
    brand: 'Samsung',
    category: 'tablets',
    rating: 4.8,
    reviews: 67,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-TAB-003',
    name: 'Samsung Galaxy Tab S8 Ultra',
    description: 'Tablet Android com tela de 14.6", 128GB, Wi-Fi',
    price: 7999.99,
    originalPrice: 9999.99,
    image: '/images/products/tab-s8-ultra.jpg',
    brand: 'Samsung',
    category: 'tablets',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-TAB-004',
    name: 'iPad Pro 12.9" (M1)',
    description: 'iPad Pro 12.9" com chip M1, 128GB, Wi-Fi',
    price: 9499.99,
    originalPrice: 10999.99,
    image: '/images/products/ipad-pro-m1.jpg',
    brand: 'Apple',
    category: 'tablets',
    rating: 4.8,
    reviews: 234,
    inStock: true,
    isPromotion: true
  },

  // Acessórios (ACC)
  {
    id: 'ELEC-ACC-001',
    name: 'Mouse Logitech G Pro X Superlight 2',
    description: 'Mouse gamer sem fio ultraleve de 60g com sensor HERO 2',
    price: 899.99,
    originalPrice: 999.99,
    image: '/images/products/gpro-superlight-2.jpg',
    brand: 'Logitech',
    category: 'acessorios',
    rating: 4.9,
    reviews: 45,
    inStock: true,
    isNew: true,
    isPromotion: true
  },
  {
    id: 'ELEC-ACC-002',
    name: 'Mouse Logitech G Pro X Superlight',
    description: 'Mouse gamer sem fio ultraleve de 63g com sensor HERO',
    price: 699.99,
    originalPrice: 899.99,
    image: '/images/products/gpro-superlight.jpg',
    brand: 'Logitech',
    category: 'acessorios',
    rating: 4.8,
    reviews: 189,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-ACC-003',
    name: 'Teclado Razer BlackWidow V3',
    description: 'Teclado mecânico gamer com switches Razer Green',
    price: 999.99,
    originalPrice: 1299.99,
    image: '/images/products/blackwidow-v3.jpg',
    brand: 'Razer',
    category: 'acessorios',
    rating: 4.7,
    reviews: 156,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-ACC-004',
    name: 'Headset Corsair Virtuoso RGB',
    description: 'Headset gamer sem fio premium com som surround 7.1',
    price: 1299.99,
    originalPrice: 1499.99,
    image: '/images/products/virtuoso-rgb.jpg',
    brand: 'Corsair',
    category: 'acessorios',
    rating: 4.8,
    reviews: 123,
    inStock: true,
    isPromotion: true
  },

  // Componentes (COMP)
  {
    id: 'ELEC-COMP-001',
    name: 'Placa de Vídeo ASUS RTX 3070 Ti',
    description: 'GPU NVIDIA RTX 3070 Ti 8GB GDDR6X',
    price: 4499.99,
    originalPrice: 5499.99,
    image: '/images/products/rtx-3070ti.jpg',
    brand: 'ASUS',
    category: 'componentes',
    rating: 4.8,
    reviews: 89,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-COMP-002',
    name: 'Processador AMD Ryzen 9 5900X',
    description: 'CPU AMD Ryzen 9 5900X 12 cores, 24 threads',
    price: 2999.99,
    originalPrice: 3499.99,
    image: '/images/products/ryzen-5900x.jpg',
    brand: 'AMD',
    category: 'componentes',
    rating: 4.9,
    reviews: 167,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-COMP-003',
    name: 'Memória RAM Corsair Vengeance RGB Pro',
    description: 'Memória RAM DDR4 32GB (2x16GB) 3600MHz RGB',
    price: 999.99,
    originalPrice: 1299.99,
    image: '/images/products/vengeance-rgb.jpg',
    brand: 'Corsair',
    category: 'componentes',
    rating: 4.7,
    reviews: 234,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'ELEC-COMP-004',
    name: 'SSD Samsung 970 EVO Plus',
    description: 'SSD NVMe M.2 1TB, leitura 3500MB/s',
    price: 799.99,
    originalPrice: 999.99,
    image: '/images/products/970-evo-plus.jpg',
    brand: 'Samsung',
    category: 'componentes',
    rating: 4.8,
    reviews: 345,
    inStock: true,
    isPromotion: true
  }
];
