import { Product } from '../../types/product';

export const mockProducts: Product[] = [
  {
    id: 'HEADP-SNY-1000X4-001',
    name: 'Sony WH-1000XM4',
    description: 'Fone de ouvido Bluetooth com cancelamento de ruído, até 30 horas de bateria',
    price: 1999.99,
    originalPrice: 2499.99,
    image: '/images/products/sony-wh1000xm4.jpg',
    brand: 'Sony',
    category: 'fones',
    rating: 4.9,
    reviews: 328,
    inStock: true,
    isNew: true,
    isFeatured: true,
    isPromotion: true
  },
  {
    id: 'SPEAK-JBL-FLIP6-001',
    name: 'JBL Flip 6',
    description: 'Caixa de som Bluetooth à prova d\'água, som potente e graves profundos',
    price: 699.99,
    originalPrice: 899.99,
    image: '/images/products/jbl-flip6.jpg',
    brand: 'JBL',
    category: 'caixas',
    rating: 4.7,
    reviews: 245,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'MICRO-SHU-SM7B-001',
    name: 'Shure SM7B',
    description: 'Microfone dinâmico profissional para podcasting e streaming',
    price: 3999.99,
    originalPrice: 4499.99,
    image: '/images/products/shure-sm7b.jpg',
    brand: 'Shure',
    category: 'microfones',
    rating: 4.9,
    reviews: 156,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'HTHEA-YAM-1840-001',
    name: 'Yamaha YHT-1840',
    description: 'Sistema Home Theater 5.1 canais com receiver e caixas acústicas',
    price: 4999.99,
    originalPrice: 5999.99,
    image: '/images/products/yamaha-yht1840.jpg',
    brand: 'Yamaha',
    category: 'home-theater',
    rating: 4.8,
    reviews: 89,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'HEADP-APP-PROV2-002',
    name: 'Apple AirPods Pro',
    description: 'Fones de ouvido sem fio com cancelamento de ruído ativo e áudio espacial',
    price: 2499.99,
    originalPrice: 2799.99,
    image: '/images/products/airpods-pro.jpg',
    brand: 'Apple',
    category: 'fones',
    rating: 4.8,
    reviews: 567,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'SPEAK-JBL-P310-002',
    name: 'JBL PartyBox 310',
    description: 'Caixa de som portátil com luzes LED, bateria de 18h e microfone sem fio',
    price: 3299.99,
    originalPrice: 3799.99,
    image: '/images/products/jbl-partybox.jpg',
    brand: 'JBL',
    category: 'caixas',
    rating: 4.7,
    reviews: 123,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'MICRO-BLU-YETIX-002',
    name: 'Blue Yeti X',
    description: 'Microfone USB profissional para streaming e gravação com LED',
    price: 1299.99,
    originalPrice: 1499.99,
    image: '/images/products/blue-yeti.jpg',
    brand: 'Blue',
    category: 'microfones',
    rating: 4.6,
    reviews: 234,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'HTHEA-SAM-Q990C-002',
    name: 'Samsung HW-Q990C',
    description: 'Soundbar 11.1.4 canais com subwoofer sem fio e Dolby Atmos',
    price: 7999.99,
    originalPrice: 8999.99,
    image: '/images/products/samsung-soundbar.jpg',
    brand: 'Samsung',
    category: 'home-theater',
    rating: 4.8,
    reviews: 78,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'HEADP-SNY-1000X4W-003',
    name: 'Sony WF-1000XM4',
    description: 'Fones de ouvido True Wireless com cancelamento de ruído e LDAC',
    price: 1699.99,
    originalPrice: 1999.99,
    image: '/images/products/sony-wf1000xm4.jpg',
    brand: 'Sony',
    category: 'fones',
    rating: 4.7,
    reviews: 345,
    inStock: true,
    isPromotion: true
  },
  {
    id: 'HTHEA-DEN-X3800H-003',
    name: 'Denon AVR-X3800H',
    description: 'Receiver AV 9.4 canais 8K com HEOS e Alexa',
    price: 9999.99,
    originalPrice: 11999.99,
    image: '/images/products/denon-receiver.jpg',
    brand: 'Denon',
    category: 'home-theater',
    rating: 4.9,
    reviews: 45,
    inStock: true,
    isPromotion: true
  }
];
