import { Product } from '../../types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'PlayStation 5',
    description: 'Console PlayStation 5 com leitor de disco, controle DualSense, 825GB SSD',
    price: 3999.99,
    originalPrice: 4499.99,
    image: '/images/products/ps5.jpg',
    brand: 'Sony',
    category: 'consoles',
    rating: 4.9,
    reviews: 567,
    isFeatured: true,
    inStock: true
  },
  {
    id: '2',
    name: 'Xbox Series X',
    description: 'Console Xbox Series X 1TB, controle sem fio, suporte 4K 120fps',
    price: 3899.99,
    originalPrice: 4299.99,
    image: '/images/products/xbox-series-x.jpg',
    brand: 'Microsoft',
    category: 'consoles',
    rating: 4.8,
    reviews: 432,
    inStock: true
  },
  {
    id: '3',
    name: 'Nintendo Switch OLED',
    description: 'Console Nintendo Switch modelo OLED com tela de 7 polegadas',
    price: 2499.99,
    originalPrice: 2799.99,
    image: '/images/products/switch-oled.jpg',
    brand: 'Nintendo',
    category: 'consoles',
    rating: 4.8,
    reviews: 345,
    isNew: true,
    inStock: true
  },
  {
    id: '4',
    name: 'God of War Ragnarök',
    description: 'Jogo God of War Ragnarök para PS5, mídia física, dublado em português',
    price: 249.99,
    originalPrice: 349.99,
    image: '/images/products/god-of-war.jpg',
    brand: 'Sony',
    category: 'jogos',
    rating: 4.9,
    reviews: 789,
    isPromotion: true,
    inStock: true
  },
  {
    id: '5',
    name: 'Controle DualSense',
    description: 'Controle sem fio DualSense para PlayStation 5, cor branca',
    price: 399.99,
    originalPrice: 499.99,
    image: '/images/products/dualsense.jpg',
    brand: 'Sony',
    category: 'acessorios',
    rating: 4.7,
    reviews: 234,
    inStock: true
  },
  {
    id: '6',
    name: 'Cadeira Gamer ThunderX3',
    description: 'Cadeira Gamer profissional, reclinável 180°, almofadas inclusas',
    price: 1499.99,
    originalPrice: 1799.99,
    image: '/images/products/thunderx3.jpg',
    brand: 'ThunderX3',
    category: 'cadeiras',
    rating: 4.6,
    reviews: 167,
    inStock: true
  },
  {
    id: '7',
    name: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'A nova aventura de Link para Nintendo Switch',
    price: 299.99,
    originalPrice: 349.99,
    image: '/images/products/zelda-totk.jpg',
    brand: 'Nintendo',
    category: 'jogos',
    rating: 4.9,
    reviews: 678,
    isNew: true,
    inStock: true
  },
  {
    id: '8',
    name: 'Headset Razer BlackShark V2 Pro',
    description: 'Headset gamer sem fio com som surround THX e microfone destacável',
    price: 999.99,
    originalPrice: 1299.99,
    image: '/images/products/razer-blackshark.jpg',
    brand: 'Razer',
    category: 'acessorios',
    rating: 4.7,
    reviews: 345,
    inStock: true
  },
  {
    id: '9',
    name: 'Cadeira Gamer DXRacer Formula',
    description: 'Cadeira ergonômica premium, estrutura em aço, espuma de alta densidade',
    price: 2499.99,
    originalPrice: 2999.99,
    image: '/images/products/dxracer.jpg',
    brand: 'DXRacer',
    category: 'cadeiras',
    rating: 4.8,
    reviews: 123,
    inStock: true
  },
  {
    id: '10',
    name: 'Xbox Series S',
    description: 'Console Xbox Series S digital, 512GB SSD, suporte 1440p 120fps',
    price: 2199.99,
    originalPrice: 2499.99,
    image: '/images/products/xbox-series-s.jpg',
    brand: 'Microsoft',
    category: 'consoles',
    rating: 4.7,
    reviews: 456,
    inStock: true
  }
];
